name: MoreLuckyBlocks
main: devjluvisi.mlb.MoreLuckyBlocks
version: 1.0
author: devjluvisi
description: A fully customizable lucky blocks plugin for Minecraft 1.17+
website: https://github.com/devjluvisi/FortuneBlocks
api-version: 1.17

commands:
  mlb:
   description: Main plugin command. Use /mlb help for more information.
   aliases: [moreluckyblocks, mluckyblocks, mlblocks, mlbplugin]