# A configuration file for all lucky blocks in MoreLuckyBlocks.
# Version: v1.0
lucky-blocks:
  default:
    item-name: "&6Lucky Block"
    block: "DIAMOND_BLOCK"
    # Lore placeholders:
    # %luck%, %default_luck%, %internal_name%, %break_perm%
    item-lore:
      - "&7A mythical lucky block of luck &c%luck%"
      - "&7Default Luck of &5%default_luck%"
    permission: "mlb.block.default"
    drops:
      '0':
        rarity: 65.0
        items:
          '0':
            type: 'SPONGE'
            amount: 64
            enchants: "[SHARPNESS:1,UNBREAKING:3]"
            display-name: "&cSuper Sponge"
            lore:
              - "&cLine 1"
              - "Line 2"
        commands:
          - "/kill %player%"
        potions:
          - "[SPEED, 1, 100]"
          - "[FAST_DIGGING, 56, 100]"
      '1':
        rarity: 65.0
        items:
          '0':
            type: 'DIAMOND_SWORD'
            amount: 1
            enchants: "[SHARPNESS:5]"
            display-name: "&4&lULTRA SWORD"
            lore:
              - "&7This sword is very good!"