name: MoreLuckyBlocks
version: '${project.version}'
main: devjluvisi.mlb.MoreLuckyBlocks
api-version: 1.17
authors: [ devjluvisi ]
description: A fully customizable and modular lucky blocks plugin designed around not having to edit configuration files.
website: https://github.com/devjluvisi/MoreLuckyBlocks

commands:
  mlb:
    description: Main plugin command. Use /mlb help for more information.
    aliases: [ moreluckyblocks, mluckyblocks, mlblocks, mlbplugin ]