name: FortuneBlocks
main: devjluvisi.fb.FortuneBlocks
version: 1.0
author: devjluvisi
description: A customizable lucky blocks plugin for Minecraft 1.17+
website: https://github.com/devjluvisi/FortuneBlocks
api-version: 1.17

commands:
  fortuneblocks:
    description: Version Command